package com.airportinfo.view.airport;

import com.airportinfo.Airport;
import com.airportinfo.view.ComponentView;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

/**
 * Showing detail of airport.
 *
 * @author lalaalal
 */
public class AirportDetailView extends ComponentView {
    private JPanel panel;
    private JTable airportDetailTable;
    private final UneditableTableModel tableModel = new UneditableTableModel(0, 2);
    private Airport airport;

    public void setAirport(Airport airport) {
        this.airport = airport;

        updateView();
    }

    @Override
    public JPanel getPanel() {
        return panel;
    }

    public void updateView() {
        while (tableModel.getRowCount() > 0)
            tableModel.removeRow(0);

        String[] keys = Airport.getLocalizedAttributeNames();
        String[] values = airport.toArray();

        for (int i = 0; i < keys.length; i++) {
            String[] row = {keys[i], values[i]};
            tableModel.addRow(row);
        }
    }

    private void createUIComponents() {
        airportDetailTable = new JTable(tableModel);
        airportDetailTable.setTableHeader(null);
        airportDetailTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        panel.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        scrollPane1.setViewportView(airportDetailTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
