package com.airportinfo;

import com.airportinfo.utils.Screenshot;
import com.airportinfo.view.ContentView;
import com.airportinfo.view.MainFrame;
import com.airportinfo.view.chart.AbstractChartView;
import com.airportinfo.view.chart.BarChartView;
import com.airportinfo.view.chart.PieChartView;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;

public class ChartContentView extends ContentView {
    private JPanel panel;
    private JButton saveButton;
    private JPanel chartViewPanel;
    private JButton toggleThemeButton;
    private JButton barButton;
    private JButton pieButton;
    private AbstractChartView chartView;
    private final PieChartView pieChartView = new PieChartView();
    private final BarChartView barChartView = new BarChartView();

    public ChartContentView(MainFrame mainFrame) {
        $$$setupUI$$$();
        setChartView(barChartView);
        saveButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Screenshot.createScreenshot(chartViewPanel, "test.png");
                    JOptionPane.showMessageDialog(panel, "Succeed", "Info", JOptionPane.INFORMATION_MESSAGE);
                } catch (IOException exception) {
                    JOptionPane.showMessageDialog(panel, exception.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }

            }
        });
        toggleThemeButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                mainFrame.toggleTheme();
            }
        });

        barButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                setChartView(barChartView);
            }
        });
        pieButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                setChartView(pieChartView);
            }
        });

        addComponentView(barChartView);
        addComponentView(pieChartView);
    }

    @Override
    public JPanel getPanel() {
        return panel;
    }

    @Override
    public void load() {
        chartView.clear();
        chartView.addLegend("apple", 10);
        chartView.addLegend("banana", 20);
        chartView.addLegend("cherry", 30);
        chartView.addLegend("dragon", 25);
        chartView.addLegend("eraser", 17);
        chartView.addLegend("fruit", 15);
        panel.revalidate();
        panel.repaint();
    }

    private void setChartView(AbstractChartView chartView) {
        this.chartView = chartView;
        chartViewPanel.removeAll();
        chartViewPanel.add(chartView.getPanel());
        load();
    }

    private void createUIComponents() {
        chartView = barChartView;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel.add(chartViewPanel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        saveButton = new JButton();
        saveButton.setText("Save");
        panel.add(saveButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        toggleThemeButton = new JButton();
        toggleThemeButton.setText("Toggle Theme");
        panel.add(toggleThemeButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
