package com.airportinfo.view;

import com.airportinfo.view.content.ContentView;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

public class TestContentView extends ContentView {
    private JPanel panel;

    public TestContentView(MainFrame mainFrame) {
        super(mainFrame);
        panel.setLayout(new BorderLayout());
    }

    @Override
    public JPanel getPanel() {
        return panel;
    }

    @Override
    public void load() {

    }

    public void setComponent(ComponentView componentView) {
        this.panel.removeAll();
        clear();
        this.panel.add(componentView.getPanel(), BorderLayout.CENTER);
        addComponentView(componentView);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
